In [3]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
np.mean(a[:,0])
# first column mean (3+8+2)/3

4.333333333333333

In [5]:
# The notation a[:,0] uses slicing
# : indicates that you want all rows.
# 0 specifies the first column (indexing starts at 0).

In [7]:
# The median is the middle value in a sorted list 
#short  first column i.e 2,3,8
np.median(a[:,0])

3.0

In [11]:
data = np.array([
    [1, 2, 3, 4, 5],  
    [5, 4, 3, 2, 1],  
    [2, 3, 4, 5, 6]   
])
# correlation coefficient formula (r)
# r = (n * Σ(xy) - Σx * Σy) / sqrt([(n * Σx^2 - (Σx)^2) * (n * Σy^2 - (Σy)^2)])
#data[:, 0] extracts the first row
#data[:, 1] extracts the second row 
np.corrcoef(data[:,0],data[:,1])

array([[1.        , 0.96076892],
       [0.96076892, 1.        ]])

In [15]:
# Population Standard Deviation Formula
# σ = sqrt( (1/N) * Σ(xi - μ)² )
# Sample Standard Deviation Formula
# s = sqrt( (1/(n-1)) * Σ(xi - x̄)² )
np.std(data[:,0])

1.699673171197595

In [17]:
# Sum of all elements
total_sum = np.sum(data)

# Sum along each row
row_sums = np.sum(data, axis=1)

# Sum along each column
column_sums = np.sum(data, axis=0)

print("Total sum:", total_sum)
print("Row sums:", row_sums)
print("Column sums:", column_sums)


Total sum: 50
Row sums: [15 15 20]
Column sums: [ 8  9 10 11 12]


In [19]:
sorted_rows = np.array([np.sort(row) for row in data])

print("Sorted rows:\n", sorted_rows)
# Sort by the second column (index 1)
sorted_by_column = data[data[:, 1].argsort()]

print("Sorted by second column:\n", sorted_by_column)

Sorted rows:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [2 3 4 5 6]]
Sorted by second column:
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [5 4 3 2 1]]


In [29]:
# Generate data
# Arguments for np.random.normal()
#1. distribution mean 
#2. distribution standard deviation
# 3.number of samples
height =np.round(np.random.normal(1.75,0.20,5000),2)
print(height)
# 1.75: This is the average height in meters.
# 0.20: This is how much the heights can vary (standard deviation).
# 5000: This is the number of heights you want to generate.
# So, this line of code creates 5000 random height values that average around 1.75 meters,
# with most values falling within about 0.20 meters of that average.
# The heights are rounded to two decimal places

[1.72 1.68 1.37 ... 1.77 1.91 1.83]


In [1]:


# # Create np_height_in from np_baseball

# np_height_in = np_baseball[:, 0]
# # Print out the mean of np_height_in

# print( np.mean(np_height_in))

# # Print out the median of np_height_in
# print(np.median(np_height_in))

NameError: name 'np_baseball' is not defined

In [ ]:
# avg = np.mean(np_baseball[:,0])
# print("Average: " + str(avg))

# # Print median height
# med = np.median(np_baseball[:, 0])
# print("Median: " + str(med))

# # Print out the standard deviation on height
# stddev = np.std(np_baseball[:, 0])
# print("Standard Deviation: " + str(stddev))

# # Print out correlation between first and second column
# corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1]) 
# print("Correlation: " + str(corr))