In [1]:
#different way Import package

In [3]:
import numpy

In [5]:
numpy.array([1,2,3])

array([1, 2, 3])

In [7]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [11]:
#math
# Import the math package
import math 

# Calculate C
C = 2 * 0.43 * math.pi
# Calculate A
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [13]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527
