In [1]:
# NumPy

In [3]:
# illustration
height =[1.73,1.68,1.71,1.79]

In [5]:
weight =[65.4,59.2,63.6,88.4]
weight

[65.4, 59.2, 63.6, 88.4]

In [7]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [33]:
#solution :Numpy
# -Numeric python
# -Alternative to python list :Numpy array
# -Calculations over entire arrays
# -Easy and Fast
# -Installation -> pip3 install numpy or !pip install numpy

In [21]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [29]:
import numpy as np
np_height=np.array(height)
print(type(np_height))
np_height

<class 'numpy.ndarray'>


array([1.73, 1.68, 1.71, 1.79])

In [17]:
np_weight=np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4])

In [31]:
bmi = np_weight/np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 27.58965076])

In [39]:
# Numpy:remarks
np.array([1,"is",True])
# Numpy arrays contain only one type

array(['1', 'is', 'True'], dtype='<U11')

In [43]:
# Create a NumPy array with integers
int_array = np.array([1, 2, 3, 4, 5])
print("Array:", int_array)
print("Data type:", int_array.dtype)

# Create a NumPy array with floats
float_array = np.array([1.0, 2.0, 3.0])
print("Array:", float_array)
print("Data type:", float_array.dtype)

# Create a NumPy array with a specified data type (string)
str_array = np.array(['a', 'b', 'c'], dtype='U1')
print("Array:", str_array)
print("Data type:", str_array.dtype)

Array: [1 2 3 4 5]
Data type: int32
Array: [1. 2. 3.]
Data type: float64
Array: ['a' 'b' 'c']
Data type: <U1


In [55]:
# Different type:different behavior
py_list = [1,2,3]
numpy_array=np.array([1,2,3])
#concatenation
py_list +  py_list


[1, 2, 3, 1, 2, 3]

In [57]:
#addition
numpy_array + numpy_array

array([2, 4, 6])

In [59]:
#Numpy Subsetting
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])      # Output: 20
print(arr[1:4])    # Output: [20 30 40]

20
[20 30 40]


In [61]:
arr[1]

20

In [67]:
arr > 20

array([False, False,  True,  True,  True])

In [71]:
arr[arr>20]

array([30, 40, 50])

In [82]:
# Slice elements from index 1 to index 5
# The result includes the start index, but excludes the end index.
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [84]:
#Slice elements from index 4 to the end of the array
print(arr[4:])

[5 6 7]


In [98]:
#Slice elements from the beginning to index 4
print(arr[:4])

[1 2 3 4]


In [90]:
#Slice from the index 3 from the end to index 1 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [92]:
# Return every other element from index 1 to index 5
# element gap gardaii return garxa
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [94]:
# Return every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [1]:
# Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [7]:

# np_weight_lb = np.array(weight_lb)
# np_height_in = np.array(height_in)

# # Print out the weight at index 50
# print(np_weight_lb[50])

# # Print out sub-array of np_height_in: index 100 up to and including index 110
# sub_array = np_height_in[100:111] 
# print(sub_array)