In [28]:
# 2D NumPy Arrays

import numpy as np
np_height =np.array([1.73,1.68,1.72])
np_weight =np.array([[65,59,3],[88,5,4]])
type(np_height)


numpy.ndarray

In [30]:
type(np_weight)

numpy.ndarray

In [32]:
#2 rows and 3 column
np_weight.shape

(2, 3)

In [37]:
#subsetting 2D NumPy Arrays
a = np.array([-1, 0.25, 0.5, 1, 2, 5, 10, 20, 30])
a[(a > 1) & (a <20)]

array([ 2.,  5., 10.])

In [44]:
# yeuta element string xa vane subaii element string ma return arxa
a = np.array([[-1, 0.25, "45",],[ 1, 2, 5]])
a

array([['-1', '0.25', '45'],
       ['1', '2', '5']], dtype='<U32')

In [50]:
a = np.array([[-1, 5, 45,],[ 1, 2, 5]])
a[0]

array([-1,  5, 45])

In [62]:
#0 index ko 2 index element
a[0][2]

45

In [60]:
# 0 index row and second index colum ko intersection element
a[0,2]

45

In [70]:
# From the second element, slice elements from index 1 to index 4 (not included):
a[:,1:3]

[7 8 9]


In [66]:
# second array lina lai
a[1,:]

array([1, 2, 5])

In [72]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [76]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [78]:
# From both elements, slice index 1 to index 4 (not included), 
# this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
