In [1]:
# Comparison Operators

In [7]:
# numpy recap
import numpy as np
np_height = np.array([1.73, 2.56, 3.23, 2.34, 3.5, 4.6, 7.4])
np_weight=np.array([55.4, 42.3, 53.2, 44.7, 56.7, 66.5, 74.3])
bmi=np_weight /np_height ** 2
bmi

array([18.51047479,  6.45446777,  5.09925332,  8.16348893,  4.62857143,
        3.14272212,  1.3568298 ])

In [9]:
bmi>23

array([False, False, False, False, False, False, False])

In [17]:
bmi[bmi>6]

array([18.51047479,  6.45446777,  8.16348893])

In [19]:
# Numeric Comparisons
2<3

True

In [21]:
4==3

False

In [23]:
2<=3

True

In [25]:
3<=3

True

In [27]:
x=3
y=4
x<y

True

In [31]:
# other comparisons
"carl"<"chris"

True

In [35]:
# comparison between integer and string
2<"carl"

TypeError: '<' not supported between instances of 'int' and 'str'

In [39]:
# comparison between integer and float
3<4.1

True

In [41]:
bmi>8

array([ True, False, False,  True, False, False, False])

In [43]:
# Comparison of booleans
True==False

# Comparison of integers
(-5*15) != 75

# Comparison of strings
"pyscript"=="PyScript"

# Compare a boolean with an integer
1==True

True

In [45]:
# Comparison of integers
x = -3 * 6
x>=-10
# Comparison of strings
y = "test"
"test"<=y

# Comparison of booleans
True >False

True

In [47]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house>=18)

# my_house less than your_house
print(my_house<your_house)

[ True  True False False]
[False  True  True False]
