In [1]:
# Boolean Operators


In [9]:
# And operator
print(True and True)
print(False and True)
print(True and False)
print(False and False)

True
False
False
False


In [11]:
x=12
x>5 and x<15
# True    True

True

In [13]:
# Or operator
print(True or True)
print(False or True)
print(True or False)
print(False or False)

True
True
True
False


In [17]:
x=12
x<5 or x>10

True

In [19]:
# Not operators
print(not True)
print(not False)

False
True


In [21]:
# But in case of Numpy array
import numpy as np
np_height = np.array([1.73, 2.56, 3.23, 2.34, 3.5, 4.6, 7.4])
np_weight=np.array([55.4, 42.3, 53.2, 44.7, 56.7, 66.5, 74.3])
bmi=np_weight /np_height ** 2
bmi

array([18.51047479,  6.45446777,  5.09925332,  8.16348893,  4.62857143,
        3.14272212,  1.3568298 ])

In [23]:
bmi>6

array([ True,  True, False,  True, False, False, False])

In [25]:
bmi<12

array([False,  True,  True,  True,  True,  True,  True])

In [27]:
bmi>6 and bmi<12

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
# In Numpy we use 
# logical_and()
# logical_or()
# logical_not()


In [39]:
print(np.logical_and(bmi>6, bmi<12))
print(bmi[np.logical_and(bmi>6, bmi<12)])

[False  True False  True False False False]
[6.45446777 8.16348893]


In [41]:
## Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house >18.5 , my_house <10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False  True False  True]
[False False False  True]


In [43]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen>10 and my_kitchen<18)

# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen<14 or my_kitchen>17)

# Double my_kitchen smaller than triple your_kitchen?
print(my_kitchen*2<3*your_kitchen)

False
True
True
